### ISSUE TITLE
Don't need the go script

### ISSUE THREAD

**Issue by MachFour** [dsewnr/linux-kitty-vim-cjk-input-plugin#1]
Hi, first of all, great idea to use Zenity! And thanks for providing the vim plugin script.

Since I don't use go for anything else, I didn't feel like installing the go compiler for this one off thing. But I realised that you can achieve the same functionality without the go script, just by putting the zenity command into vimscript:

```
function CJKInput()
    let l:cmd = 'zenity --entry --text=CJK-Input'
    let l:output = system(l:cmd)
    let l:output = substitute(l:output, '[\r\n]*$', '', '')
    execute 'normal i' . l:output
endfunction
nmap <silent> <leader>j :call CJKInput()<CR>
```

**Comment by MachFour** [comment]
by the way, this also removes the need for xclip

**Comment by dsewnr** [comment]
What a better way ! Thank you, @MachFour .
